include: package:pedantic/analysis_options.yaml
# include: package:effective_dart/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - camel_case_types
    - prefer_const_constructors